version: '3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: <endpoint_do_rds>
      WORDPRESS_DB_USER: <usuario_do_rds>
      WORDPRESS_DB_PASSWORD: <senha_do_rds>
      WORDPRESS_DB_NAME: <identificador_do_rds>
